name: Test GitHub Action

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  test-matrix:

    strategy:
      matrix:
        node_version: [16, 18, 19]
        os: [macos-latest, ubuntu-latest, windows-latest] # 只写这个，不用它，二维数组也会生效！
      fail-fast: false # default value: true
      # max-parallel: 3 # 只限制同时运行的数量，不限制总的数量 # 好像也没有很
    # runs-on: [self-hosted, macOS, ARM64, M1, test, office]
    runs-on: ${{ matrix.os }}

    steps:
      - name: log node version
        run: node -v
      
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: log node version again
        run: node -v