name: Run unit test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  run-unit-test:
    # runs-on: [self-hosted, macOS, ARM64, M1, test, office]
    runs-on: [self-hosted, macOS, ARM64, CompanyMac]
    # runs-on: [self-hosted, macOS, ARM64, antony, m1pro]

    steps:
      # 似乎这个action还不支持M1的mac，是不是后面可以自己弄一个setup ruby的私有action？
      # https://github.com/ruby/setup-ruby/issues/341
      # - name: Set up Ruby to 3.1.2
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1.2'
      #   env:
      #     ImageOS: macos12

      # source ~/.zshrc # 反斜杠后不能有空格
      # source ~/.zprofile # 执行这个之后，PATH才会更新
      # source ~/.zshrc # 执行这个，是更新「.zshrc」文件
      - name: whoami
        # shell: sh
        run: |
          source ~/.zprofile
          source ~/.zshrc
          whoami
          echo "$PATH"
          type -a ruby
          which ruby
          ruby --version

      # asdf list
      # asdf global ruby 3.1.2
      - name: Setup ruby
        run: |
          brew install asdf
          echo -e "\n. $(brew --prefix asdf)/libexec/asdf.sh" >> ${ZDOTDIR:-~}/.zshrc
          asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
          asdf install ruby 3.1.2
          asdf global ruby 3.1.2

      - name: whoami 2
        run: |
          whoami
          asdf list ruby
          echo "$PATH"
          type -a ruby
          which ruby
          ruby --version

      - name: whoami 3
        run: |
          source ~/.zprofile
          source ~/.zshrc
          whoami
          asdf list ruby
          echo "$PATH"
          type -a ruby
          which ruby
          ruby --version

      - name: Check out
        uses: actions/checkout@v3

      - name: Install bundler
        run: |
          source ~/.zprofile
          source ~/.zshrc
          gem install bundler

      - name: Run bundle install
        run: |
          source ~/.zprofile
          source ~/.zshrc
          bundle install

      # - name: Run unit test
      #   run: bundle exec fastlane run_unit_test
      #   # https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
      #   env:
      #     LC_ALL: en_US.UTF-8
      #     LANG: en_US.UTF-8
