name: Run unit test

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  run-unit-test:
    # runs-on: [self-hosted, macOS, ARM64, M1, test, office]
    runs-on: [self-hosted, macOS, ARM64, CompanyMac]

    steps:
      # 似乎这个action还不支持M1的mac，是不是后面可以自己弄一个setup ruby的私有action？
      # https://github.com/ruby/setup-ruby/issues/341
      # - name: Set up Ruby to 3.1.2
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1.2'
      #   env:
      #     ImageOS: macos12

      - name: source ~/.zshrc
        run: |
          source ~/.zshrc

      - name: whoami
        run: |
          whoami
          echo "$PATH"
          type -a ruby
          which ruby
          ruby --version

      # asdf list
      # asdf global ruby 3.1.2
      # - name: Setup ruby
      #   run: |

      - name: Check out
        uses: actions/checkout@v3

      - name: whoami 2
        run: |
          whoami
          echo "$PATH"
          type -a ruby
          which ruby
          ruby --version

      - name: Install bundler
        run: gem install bundler

      - name: Run bundle install
        run: bundle install

      # - name: Run unit test
      #   run: bundle exec fastlane run_unit_test
      #   # https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
      #   env:
      #     LC_ALL: en_US.UTF-8
      #     LANG: en_US.UTF-8
