name: Run unit test(xcodebuild test)

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  run-unit-test:
    runs-on: [self-hosted, macOS, ARM64, M1, test, office]
    # runs-on: [self-hosted, macOS, ARM64, CompanyMac]
    # runs-on: [self-hosted, macOS, ARM64, antony, m1pro]

    steps:
      - name: Setup for Mapbox
        run: |
          pwd
          touch .netrc
          open .netrc
          echo "machine api.mapbox.com\nlogin mapbox\npassword '${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}'" > .netrc

      - name: Check out
        uses: actions/checkout@v3

      - name: Run unit test (xcodebuild test)
        run: |
          xcodebuild -version
          xcodebuild test -project 'TestCICD.xcodeproj' -scheme 'TestCICD' -destination 'platform=iOS Simulator,name=iPhone 14'
