name: Run unit test(xcodebuild single job)

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  run-unit-test:
    runs-on: [self-hosted, macOS, ARM64, M1, test, office]
    # runs-on: [self-hosted, macOS, ARM64, CompanyMac]
    # runs-on: [self-hosted, macOS, ARM64, antony, m1pro]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Decrypt Config.xcconfig for project
        run: |
          pwd
          openssl enc -d -aes-256-cbc -in TestCICD/Config.xcconfig.enc -out TestCICD/Config.xcconfig -k ${{ secrets.CONFIG_FILE_DECRYPT_PASSWORD }}

      - name: Setup private token for Mapbox
        run: |
          cd ~
          pwd
          touch .netrc
          open .netrc
          echo -e 'machine api.mapbox.com\nlogin mapbox\npassword ${{ secrets.MAPBOX_PRIVATE_TOKEN }}' > .netrc
          
      # xcodebuild test -project 'TestCICD.xcodeproj' -scheme 'TestCICD' -destination 'platform=iOS Simulator,name=iPhone 14'
      - name: Run unit test (xcodebuild test)
        run: |
          pwd
          xcodebuild -version

      # rm TestCICD/Config.xcconfig
      - name: Delete confidential info from CI environment
        run: |
          pwd    
          cd ~
          pwd
          rm .netrc
